import styles from "../../../../../styles/Season.module.css";
import { useRouter } from "next/router";
import { useState, useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import { FaAngleLeft, FaAngleRight } from "react-icons/fa";
import Link from "next/link";
import EpisodeCard from "../../../../../components/EpisodeCard";

const season = () => {
  const router = useRouter();
  const { id, sid } = router.query;
  const [seasonData, setSeasonData] = useState(null);
  const [episodeData, setEpisodeData] = useState(null);

  useEffect(() => {
    if (!id) return;
    fetch(
      `https://api.tvmaze.com/singlesearch/shows?q=${id
        .replace(/_/g, " ")
        .replace(/:/g, "")}&embed[]=seasons`
    )
      .then((res) =>
        res
          .json()
          .then((resData) => setSeasonData(resData))
          .catch((err) => console.log(err))
      )
      .catch((err) => console.log(err));
  }, [id]);

  useEffect(() => {
    if (!sid || !seasonData) return;
    fetch(
      `https://api.tvmaze.com/seasons/${
        seasonData._embedded.seasons[parseInt(sid) - 1].id
      }/episodes`
    )
      .then((res) =>
        res
          .json()
          .then((resData) => setEpisodeData(resData))
          .catch((err) => console.log(err))
      )
      .catch((err) => console.log(err));
  }, [sid, seasonData]);

  useEffect(() => {
    if (!seasonData || !episodeData) return;
    let summary = document.getElementById("summary");
    summary.innerHTML = seasonData._embedded.seasons[parseInt(sid) - 1].summary
      ? seasonData._embedded.seasons[parseInt(sid) - 1].summary
      : "<p>Summary Unavailable</p>";
    // delete later
    console.log(seasonData);
    console.log(episodeData);
  }, [seasonData, episodeData]);

  return (
    episodeData &&
    seasonData && (
      <>
        <Head>
          <title>
            {seasonData.name} - S{sid}
          </title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
          <h2 className={styles.title}>
            {seasonData.name} - Season {sid}
          </h2>
          {/* image and summary section */}
          <section className={styles.information}>
            <div className={styles.imageWrapper}>
              <Image
                src={seasonData.image.original}
                alt={seasonData.name}
                width={200}
                height={200}
                placeholder="blur"
                blurDataURL={seasonData.image.medium}
              />
            </div>
            <div className={styles.textWrapper}>
              <div id="summary" className={styles.summary}></div>
              <div className={styles.navbar}>
                <Link
                  href={`/shows/${id}/seasons/${
                    parseInt(sid) === 1
                      ? seasonData._embedded.seasons.length
                      : parseInt(sid) - 1
                  }`}
                >
                  <a>
                    <div className={styles.nav}>
                      <FaAngleLeft /> Prev
                    </div>
                  </a>
                </Link>
                <Link
                  href={`/shows/${id}/seasons/${
                    parseInt(sid) === seasonData._embedded.seasons.length
                      ? 1
                      : parseInt(sid) + 1
                  }`}
                >
                  <a>
                    <div className={styles.nav}>
                      Next <FaAngleRight />
                    </div>
                  </a>
                </Link>
              </div>
            </div>
          </section>
          {/* episodes section */}
          <h3 className={styles.episodeTitle}>Episodes</h3>
          <div className={styles.episodeWrapper}>
            {episodeData.map((data, key) => {
              return (
                <div key={key}>
                  <EpisodeCard data={data} uniqueKey={key} />
                </div>
              );
            })}
          </div>
        </main>
      </>
    )
  );
};

export default season;
